### ISSUE TITLE
Using the e option rather than the x option does not preserve folder structure

### ISSUE THREAD

**Issue by debugme** [scopsy/node-unrar#4]
If you expand a RAR file which contains folders, those folders are not preserved in the final output.
Running "unrar e m.rar" at the terminal mimics this behaviour.
Running "unrar x m.rar" expands the file while preserving the folder structure, however.

Perhaps you can use your options object to allow the caller to decide whether to use "e" or "x" as the command to use with unrar?

**Comment by scopsy** [comment]
I'm really busy currently, we can defiantly pass an object instead of the null parameters(that's was my initial intention).

Feel free to make pull request for that, if not, I will try to add this functionality when i'll have some free time.
